### ISSUE TITLE
Bug: Out of order wrap around requires specific sequence value

### ISSUE THREAD

**Issue by benjaminauer** [k-yle/sACN#37]
When sequence does not go up to 255, skips it for any reason, the sequence gets out of order for the remainder of the duration the process is running.

https://github.com/k-yle/sACN/blob/eae3d83fc07a57a13b926fc40d46f445bb599d55/src/receiver.ts#L65-L66

**Comment by k-yle** [comment]
Hi @benjaminauer, I've opened #38 which should fix this - only one error will be emitted, then it will use the latest sequence. let me know if that PR works for you. Otherwise I'll release the fix tomorrow

**Comment by benjaminauer** [comment]
will be able to check it on friday 16.07.21
found the issue when every second packet was always tagged with packetcorruption.
sender is an ETC paradigm processor. i will try to track the issue down and create another issue later on

**Comment by benjaminauer** [comment]
i could not try it in my theatre today,
but i tried some stuff at home now, they way this lib handles the packet sequence, it will throw an error, when multiple senders are active in a network. it needs a per source / per universe comparsion to check order of packets

**Comment by hansSchall** [comment]
Having the same bug with a ETC IonXE20 Eos 3.1.0 Build 282 and sACN Version 4.1.0

My Software is listening to universe 2, Ion is transmitting universe 2, Another Device is transmitting universe 1.

Log looks like this:

Error: Packet significantly out of order in universe 2 (254 -> 27)
    at Socket.<anonymous> (D:\technik\software\sACN2Video\server\node_modules\sacn\dist\receiver.js:26:27)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)
Error: Packet significantly out of order in universe 2 (254 -> 28)
    at Socket.<anonymous> (D:\technik\software\sACN2Video\server\node_modules\sacn\dist\receiver.js:26:27)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)
Error: Packet significantly out of order in universe 2 (254 -> 30)
    at Socket.<anonymous> (D:\technik\software\sACN2Video\server\node_modules\sacn\dist\receiver.js:26:27)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)
Error: Packet significantly out of order in universe 2 (254 -> 31)
    at Socket.<anonymous> (D:\technik\software\sACN2Video\server\node_modules\sacn\dist\receiver.js:26:27)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)
Error: Packet significantly out of order in universe 2 (254 -> 32)
    at Socket.<anonymous> (D:\technik\software\sACN2Video\server\node_modules\sacn\dist\receiver.js:26:27)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)

_and so on from 1 to 233_

Sometimes I get this error, sometimes not.

I will try to get a log of all the sACN messages.

**Comment by hansSchall** [comment]
OK, I found the Bug:

if there is a OutOfOrderError, the lastSequence is not updated to the last value.
If the is one Seqence number missing the error is thrown until one cycle of sequence numbers is completed.

**Comment by k-yle** [comment]
I've updated PR #38 so that there should be no `PacketOutOfOrder` errors if there are two consoles broadcasting to the same universe. Tested with one laptop running Martin M-PC and another laptop running LightFactory.

I'm going to merge #38 tomorrow since this seems to properly fix the issue.

@hansSchall, this means we won't need the flag you suggested
